// import type { FooterItem, MainNavItem } from "@/types"
//
// import { productCategories } from "@/config/products"
// import { slugify } from "@/lib/utils"

import { Icons } from '@/components/icons';
import { env } from '@/env.mjs';

export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: env.NEXT_PUBLIC_SITE_NAME,
  author: env.NEXT_PUBLIC_SITE_NAME,
  slogan: 'Watch TV Shows Online, Watch Movies Online.',
  description:
    'Watch movies & TV shows online or stream right to your smart TV, game console, PC, Mac, mobile, tablet and more.',
  keywords: [
    'watch movies',
    'movies online',
    'watch TV',
    'TV online',
    'TV shows online',
    'watch TV shows',
    'stream movies',
    'stream tv',
    'instant streaming',
    'watch online',
    'movies',
    'watch TV online',
    'no download',
    'full length movies',
    'Watch Movies Online',
'Free Streaming Movies',
'HD Movies Online',
'Watch TV Shows Online',
'Stream TV Shows Free',
'Latest Movie Releases',
'Free TV Streaming',
'HD Streaming Service',
'Full-Length Movies Free',
'Watch TV Free',
'Action Movies Online',
'Romantic Movies Streaming',
'Comedy Movies Online',
'Horror Movies Free',
'Sci-Fi Movies Streaming',
'Documentaries Free Online',
'Kids Movies Streaming',
'Thriller Movies Online',
'Animated Movies Free',
'Adventure Movies HD',
'Stream Movies on Smart TV',
'Watch Movies on Mobile',
'Free Movies on PC',
'TV Shows on Tablets',
'Movies for Xbox Streaming',
'PS5 Movie Streaming',
'Watch on Game Consoles',
'Stream on Roku',
'Apple TV Streaming',
'Chromecast Free Movies',
'Free Movies in the US',
'Watch Movies in the UK',
'Movies Free in Canada',
'TV Shows in India',
'Global Streaming Service',
'Movies Free Worldwide',
'Watch Asian Movies Online',
'European TV Shows Streaming',
'Bollywood Movies Free',
'Korean Dramas Online',
'Ad-Free Movie Streaming',
'No Registration Movies',
'Unlimited Streaming Free',
'Watch Offline Movies',
'Free HD Downloads',
'No Subscription Movies',
'Instant Movie Streaming',
'Free 4K Movies Online',
'Multiple Device Streaming',
'Parental Control Streaming',
'Latest 2024 Movies Online',
'Trending TV Shows Free',
'Top Movies of the Month',
'New Movie Releases 2024',
'Free Oscar Movies Online',
'Popular TV Series Streaming',
'Top Picks for Streaming',
'Golden Globe Movies Free',
'Box Office Hits Streaming',
'Top TV Shows Free',
'Best Websites to Stream Movies',
'How to Watch Free Movies Online',
'Top Platforms for TV Shows',
'Where to Watch Movies Online',
'Free Streaming Without Ads',
'Movies Without Signup Needed',
'Best Platforms for HD Movies',
'Free Streaming with Subtitles',
'Top Sites for Family Movies',
'Latest Movies with No Download',
'Watch Independent Films Online',
'Stream Documentaries Free',
'Classic Movies Online Free',
'LGBTQ+ Movies Streaming',
'Festival Films Free Online',
'Anime Movies Free Streaming',
'Old Hollywood Movies Online',
'Free Educational Movies',
'Biographical Films Free',
'Black-and-White Movies Online',
'Best Alternatives to Netflix',
'Free Disney+ Movies Online',
'Hulu Alternative Streaming',
'Amazon Prime Movies Free',
'Best Free HBO Shows',
'Crackle Movies Free Online',
'Pluto TV Shows Free',
'Free Peacock TV Streaming',
'Free Movies Similar to M4UHD',
'YouTube Free Movie Streaming',
'TV and Movie Reviews Online',
'Free Streaming Forums',
'Movie Ratings and Reviews',
'Compare Streaming Services',
'Free Movie Night Ideas',
'Online Watch Party Services',
'New Movie Trailers Online',
'Best Movie Streaming Deals',
'User-Friendly Streaming Apps',
'Free Subtitled Movies',
    'Stream Free Movies',
'Watch Movies in HD',
'Top Movies Online',
'Best TV Shows to Watch',
'Free Movie Streaming Sites',
'Watch TV for Free',
'Watch TV Shows in HD',
'Free Online Movie Streaming',
'Free TV Shows Streaming',
'Watch Latest Movies Online',
'Best Free Streaming Websites',
'Movies Free Online',
'Free TV Streaming Sites',
'Instant Movie Streaming',
'Free Full-Length Movies',
'Watch Movies Without Sign Up',
'No Download Movies Free',
'Free Movies to Watch Now',
'Watch Latest TV Shows Online',
'TV Show Streaming Free',
'Stream Movies on Roku',
'Watch Free Movies HD',
'Stream Free TV Shows',
'Watch Free TV Shows Online',
'Best Free Movies to Watch',
'Free Streaming Without Signup',
'Top Online Streaming Sites',
'Stream Movies Free HD',
'Popular Movies Streaming',
'Best Sites for TV Shows',
'Free TV Streaming with Subtitles',
'Free Movies in HD Online',
'Top Movies for Streaming',
'Free TV Shows in HD',
'Full-Length Movies Free Online',
'Free Movies on Android',
'Watch Movies Online Without Download',
'HD Movie Streaming Sites',
'Watch Popular Movies Online',
'Free TV Shows Online Streaming',
'Best Streaming Platforms',
'Watch Movie Trailers Free',
'Watch TV Series for Free',
'Latest Movies to Watch Online',
'Free Documentaries Streaming',
'Free Movies on Amazon Prime',
'Free Streaming with No Ads',
'Stream Movies Online Free',
'Watch Movies on Smart Devices',
'Best Sites for Free Movies',
'Free Movies on YouTube',
'Free TV Shows on YouTube',
'Popular TV Shows to Watch',
'Free High-Quality Movies',
'Watch Movies Without Signup Required',
'Stream Full Movies Free',
'Movies to Watch Online Now',
'Watch Latest Shows on Mobile',
'Stream TV Shows Without Ads',
'Best Free TV Streaming Sites',
'Free Movies for Kids',
'Latest Free Movies Online',
'Free Movies on iPhone',
'Watch HD TV Shows Online',
'Watch TV on Smart TV Free',
'Top Free TV Channels Streaming',
'Watch HD Movies Without Subscription',
'Streaming Sites for TV Shows',
'Watch Movies on Firestick',
'Free Streaming for Movies and TV',
'No Sign Up Movie Streaming',
'Stream Free Movie Websites',
'Watch Movies Online Anytime',
'HD TV Shows Streaming Free',
'Free TV Channels Online',
'Watch Movies and TV Shows Free',
'Stream Movie Apps for iPhone',
'Free TV Shows on Amazon Prime',
'Full Movies Online Streaming',
'Free Full Movies to Watch',
'Free Movie Streaming Services',
'Stream Movies and TV Shows Free',
'Stream Movies in High Quality',
'Latest Shows Streaming Free',
'Free Streaming with No Membership',
'Top Free Movie Streaming Services',
'Best Streaming Services for TV Shows',
'Stream TV Free on Chromecast',
'Free Movie Streaming with Subtitles',
'Watch TV Free Streaming Online',
'Top 10 Free Movie Sites',
'Watch Movies and Shows for Free',
'HD Movies Streaming for Free',
'Popular TV Shows Free Streaming',
'Free Movies with English Subtitles',
'Best Movies Free Streaming Online',
'Streaming Sites for HD Movies',
'Free Streaming No Membership',
'Watch Free TV Shows Without Registration',
'Top Movie Streaming Platforms',
'Free Movies to Watch Now Online',
'Watch Movies with No Login',
'Stream Free Shows Online',
'Free Movie Streaming Apps',
'Watch Movies on Chromecast',
'Best Movies Streaming Services',
'Free Movies on Smart TV',
'Movies for Free Streaming Online',
'HD Streaming Movies Free',
'Watch Latest Movies Without Signup' ,
    'Watch Movies on Smart TV Free',
'Best TV Streaming Services',
'Watch Full Movies Online Free',
'HD Movie Streaming Online',
'Stream Movies No Signup Required',
'Free Online Movie Sites',
'Watch Free Movies Without Signup',
'Stream TV Shows on iPhone',
'Watch TV Shows for Free HD',
'Best Sites for Watching Movies Online',
'Top Free Movie Streaming Websites',
'Stream Movies Online HD',
'Watch Movies on Firestick Free',
'Movies to Stream Online Free',
'Free Movies to Stream Online',
'Stream Movies on Roku Free',
'Watch Latest Movies Online Free',
'Movies Streaming No Subscription',
'Free Streaming Movie Sites No Download',
'Watch Movies on PC Free',
'Free Streaming Services for Movies',
'Watch TV Shows on Roku Free',
'Free HD TV Shows to Watch',
'Watch Movies Online No Download',
'Free Streaming TV Shows Online',
'Stream Movies on Apple TV',
'Free Online Movie Streaming Sites',
'Stream Movies Online Without Registration',
'Stream Movies Free Online Without Ads',
'Watch HD Movies Online Free',
'Movies to Watch Online Free Streaming',
'Stream Movies Without Sign-Up',
'Best Free Movie Apps',
'Watch TV Shows Online Without Signup',
'Free Movie Streaming Apps for Android',
'Movies for Free Online',
'Streaming TV and Movies Free',
'Watch TV Shows Free No Signup',
'Watch Movies for Free HD',
'Stream Full-Length Movies Free',
'Free Streaming No Credit Card',
'Best Movies Streaming Free Online',
'Free Streaming Movies No Sign Up',
'Top Free Movie Websites',
'Best Streaming Websites for TV Shows',
'Free TV Shows to Watch Online',
'Free Movie Sites for PC',
'Movies Streaming for Free on TV',
'Stream Movies and TV Shows Free Online',
'HD Free Movies Online Streaming',
'Watch Movies in Full HD Free',
'Free Movie Sites with Subtitles',
'Stream Movies Without Ads Free',
'Free Movie Streaming for PC',
'Watch TV Shows Without Sign Up Free',
'Stream Free Full-Length Movies',
'Watch Free Streaming TV Shows',
'Latest TV Shows Streaming Free',
'Watch Movies on Game Console Free',
'Free Movies Streaming App for Android',
'Watch Free Movies on Tablets',
'Top Free TV Shows Online',
'Best Free Streaming Apps for TV Shows',
'Free TV Streaming No Signup',
'Movies Streaming Free No Signup',
'Free Streaming HD Movies on Roku',
'Top Free Streaming Sites for Movies',
'Free Streaming for Movies and TV Shows',
'Free TV Shows on Mobile',
'Free Movies Without Registration',
'Watch TV Series Without Signup',
'Best Free Streaming Movie Sites',
'Stream Movies Free without Ads',
'Top Streaming Sites for Movies',
'Watch Movies Without Ads Free',
'HD Streaming TV Shows Free',
'Stream Movies on Chromecast Free',
'Watch TV Shows on Xbox Free',
'Movies and TV Free Streaming',
'Best Free Streaming Websites for Movies',
'Free TV Shows Streaming No Signup',
'Watch Movies on iPad Free',
'Free Full Movies to Watch Online',
'Watch Free Movies Without Registration',
'Top Sites for Streaming Movies Free',
'Watch TV Shows on Firestick Free',
'Stream Movies and TV Shows HD',
'Top Free Movie Streaming Apps',
'Watch Free Movies on iPhone',
'Free Online Streaming for Movies and TV',
'Best Streaming Platforms for Movies',
'Free Streaming Movies No Subscription',
'Stream Movies and TV Shows Without Signup',
'Watch Movies Free Online No Sign-Up',
'Free Movies in HD No Signup',
'Watch Free Movies on Your Phone',
'Free TV Streaming on iPhone',
'Best Free TV Streaming Apps',
'Stream Movies Free HD on Apple TV',
'Free TV Series on Android',
'Watch Free Movies and TV Shows HD',
'Watch Movies Online on Roku Free',
'Movies to Stream Without Subscription',
'Best Sites for Free TV Shows',
'Watch Movies and TV Shows on Your Phone',
'Free TV Shows with Subtitles',
'Stream Free Movies Without Signup on Roku',
'Free Movie Sites with No Registration',
'Watch Free Movies on PS5',
'Watch TV Shows on Apple TV',
'Top 10 Free Movie Streaming Apps',
'Free TV Streaming Without Registration',
'Free Movies for Streaming Online',
'Stream Free Movies Without Ads HD',
'Best Movie Streaming Free Apps',
'Free Streaming Sites for Movies HD',
'Movies Free Online on TV',
'Free Movie Streaming Services for Android',
'Free HD Movies on Roku',
'Movies Streaming Free No Credit Card',
'Watch Movies Online Without Paying',
'Free TV Shows with No Signup',
'HD TV Shows Online Streaming Free',
'Stream Movies Online with No Signup',
'Top Free Movie Sites Without Ads',
'Free Streaming Without Signup for TV',
'Best Free TV Streaming Websites',
'Watch TV Shows for Free on Android',
'Movies to Watch Free Streaming No Signup',
'Best Free Movie Sites No Ads',
'Free Streaming Sites for Full Movies',
'Watch Movies Online Without Signup Free',
'Stream Free TV Shows on Smart TV',
'Free Movie Streaming Sites No Credit Card',
'Watch Latest Movies Without Subscription',
'Watch TV Shows on Your Phone Free',
'Free Movie Websites Without Registration',
'Top Free TV Streaming Sites',
'Best Free Movie Streaming Apps for Android',
'Top Free TV Shows Streaming Apps',
'Free Full HD Movies Streaming Sites',
'Stream Free Movies on Roku Without Signup',
'Watch TV Shows Without Subscription',
'Top Free Streaming Apps for Movies',
'Watch Movies Online HD for Free',
'Watch TV Shows Online Free No Signup',
'Free Streaming Movies with Subtitles',
'Best Free Online Movie Streaming Sites',
'Watch Movies and TV Shows Online Free',
'Free HD Movies and TV Shows Streaming',
'Free Streaming Movies Without Credit Card',
'Watch Full Movies Without Signup Free',
'Stream Movies on Apple TV Free',
'Top Free Movies Streaming Services',
'Watch Movies Without Signup Free Online',
'Free TV Shows No Sign Up Required',
'Best Free Movie Apps for Android',
'Movies Streaming Online Free No Signup',
'Watch Free Movies on Chromecast',
'Watch Movies on Your PC for Free',
'Free Streaming Movies on Firestick',
'Best TV Shows Streaming Sites Free',
'Free Streaming Apps for HD Movies',
'Watch Movies on Xbox Without Signup',
'Stream Movies Without Sign-Up HD',
'Free TV Shows and Movies Streaming',
'Stream Movies Free on PS5',
'Free Movie Streaming Sites HD',
'Free TV Movies Streaming Online',
'Stream Movies HD Free Online',
'Free HD Movies Online without Sign-Up',
'Watch Free Movies Without Signing Up',
'Free Movies Streaming HD on Roku',
'Stream Full Movies for Free Online',
'Free Streaming Movies Without Signup HD',
'Watch Movies on Firestick Free',
'Top Streaming Platforms for Movies',
'Free TV Streaming Without Signup HD',
'Free Full Movies to Stream Online',
'Watch Movies Free on iPad',
'Best Sites for Streaming Movies HD',
'Free TV Shows Online without Signup',
'Free Movie Streaming Sites HD Free',
    env.NEXT_PUBLIC_SITE_NAME,
  ],
  url: env.NEXT_PUBLIC_APP_URL,
  ogImage: `${env.NEXT_PUBLIC_APP_URL}/images/hero.jpg`,
  links: {
    twitter: `${env.NEXT_PUBLIC_TWITTER}`,
    github: 'https://github.com/Anuraagsingh132/streamverse',
    githubAccount: '',
  },
  socialLinks: [
    {
      title: 'Facebook',
      href: `${env.NEXT_PUBLIC_FACEBOOK}`,
      icon: Icons.facebook,
    },
    {
      title: 'Instagram',
      href: `${env.NEXT_PUBLIC_INSTAGRAM}`,
      icon: Icons.instagram,
    },
    {
      title: 'Twitter',
      href: `${env.NEXT_PUBLIC_TWITTER}`,
      icon: Icons.twitter,
    },
    {
      title: 'Youtube',
      href: `${env.NEXT_PUBLIC_YOUTUBE}`,
      icon: Icons.youtube,
    },
  ],
  footerItems: [
    { title: 'Audio Description', href: '/' },
    { title: 'Help Center', href: '/' },
    { title: 'Gift Cards', href: '/' },
    { title: 'Media Center', href: '/' },
    { title: 'Investor Relations', href: '/' },
    { title: 'Jobs', href: '/' },
    { title: 'Terms of Use', href: '/terms-of-use' },
    { title: 'Privacy', href: '/' },
    { title: 'Legal Notices', href: '/' },
    { title: 'Cookie Preferences', href: '/' },
    { title: 'Corporate Information', href: '/' },
    { title: 'Contact Us', href: '/' },
  ],
  mainNav: [
    {
      title: 'Home',
      href: '/home',
      // icon: Icons.play,
    },
    {
      title: 'TV Shows',
      href: '/tv-shows',
      // icon: Icons.tvShow,
    },
    {
      title: 'Movies',
      href: '/movies',
      // icon: Icons.movie,
    },
    {
      title: 'New & Popular',
      href: '/new-and-popular',
      // icon: Icons.trendingUp,
    },
    {
      title: 'About',
      href: 'https://developer.streamverse.biz',
      // icon: Icons.trendingUp,
    },
    
    // {
    //   title: "My List",
    //   href: "/my-list",
    //   // icon: Icons.list,
    // },
    {
      title: 'Notifications',
      // onClick: () => alert("🛹 Do a kickflip"),
      // icon: Icons.bell,
    },
  ],
};
